// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AetheryteData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AetheryteData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAetheryteData(bb:flatbuffers.ByteBuffer, obj?:AetheryteData):AetheryteData {
  return (obj || new AetheryteData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAetheryteData(bb:flatbuffers.ByteBuffer, obj?:AetheryteData):AetheryteData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AetheryteData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

aetheryteId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startAetheryteData(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addAetheryteId(builder:flatbuffers.Builder, aetheryteId:number) {
  builder.addFieldInt32(0, aetheryteId, 0);
}

static endAetheryteData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAetheryteData(builder:flatbuffers.Builder, aetheryteId:number):flatbuffers.Offset {
  AetheryteData.startAetheryteData(builder);
  AetheryteData.addAetheryteId(builder, aetheryteId);
  return AetheryteData.endAetheryteData(builder);
}
}
