// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class DiscoveryMask {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DiscoveryMask {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDiscoveryMask(bb:flatbuffers.ByteBuffer, obj?:DiscoveryMask):DiscoveryMask {
  return (obj || new DiscoveryMask()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDiscoveryMask(bb:flatbuffers.ByteBuffer, obj?:DiscoveryMask):DiscoveryMask {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DiscoveryMask()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mask():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startDiscoveryMask(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMask(builder:flatbuffers.Builder, mask:number) {
  builder.addFieldInt32(0, mask, 0);
}

static endDiscoveryMask(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDiscoveryMask(builder:flatbuffers.Builder, mask:number):flatbuffers.Offset {
  DiscoveryMask.startDiscoveryMask(builder);
  DiscoveryMask.addMask(builder, mask);
  return DiscoveryMask.endDiscoveryMask(builder);
}
}
