// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DynamicMarkerData } from './dynamic-marker-data.js';


export class DynamicMarker {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DynamicMarker {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDynamicMarker(bb:flatbuffers.ByteBuffer, obj?:DynamicMarker):DynamicMarker {
  return (obj || new DynamicMarker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDynamicMarker(bb:flatbuffers.ByteBuffer, obj?:DynamicMarker):DynamicMarker {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DynamicMarker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

objectiveId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

label():string|null
label(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
label(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

data(index: number, obj?:DynamicMarkerData):DynamicMarkerData|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new DynamicMarkerData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

recommendedLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

shouldRender():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startDynamicMarker(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addObjectiveId(builder:flatbuffers.Builder, objectiveId:number) {
  builder.addFieldInt32(0, objectiveId, 0);
}

static addLabel(builder:flatbuffers.Builder, labelOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, labelOffset, 0);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRecommendedLevel(builder:flatbuffers.Builder, recommendedLevel:number) {
  builder.addFieldInt16(3, recommendedLevel, 0);
}

static addShouldRender(builder:flatbuffers.Builder, shouldRender:boolean) {
  builder.addFieldInt8(4, +shouldRender, +false);
}

static endDynamicMarker(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDynamicMarker(builder:flatbuffers.Builder, objectiveId:number, labelOffset:flatbuffers.Offset, dataOffset:flatbuffers.Offset, recommendedLevel:number, shouldRender:boolean):flatbuffers.Offset {
  DynamicMarker.startDynamicMarker(builder);
  DynamicMarker.addObjectiveId(builder, objectiveId);
  DynamicMarker.addLabel(builder, labelOffset);
  DynamicMarker.addData(builder, dataOffset);
  DynamicMarker.addRecommendedLevel(builder, recommendedLevel);
  DynamicMarker.addShouldRender(builder, shouldRender);
  return DynamicMarker.endDynamicMarker(builder);
}
}
