// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vector3 } from './vector3.js';


export class DynamicMarkerData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DynamicMarkerData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDynamicMarkerData(bb:flatbuffers.ByteBuffer, obj?:DynamicMarkerData):DynamicMarkerData {
  return (obj || new DynamicMarkerData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDynamicMarkerData(bb:flatbuffers.ByteBuffer, obj?:DynamicMarkerData):DynamicMarkerData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DynamicMarkerData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

levelId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

objectiveId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

tooltip():string|null
tooltip(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
tooltip(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

icon():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

position(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

mapId():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

dataId():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startDynamicMarkerData(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addLevelId(builder:flatbuffers.Builder, levelId:number) {
  builder.addFieldInt32(0, levelId, 0);
}

static addObjectiveId(builder:flatbuffers.Builder, objectiveId:number) {
  builder.addFieldInt32(1, objectiveId, 0);
}

static addTooltip(builder:flatbuffers.Builder, tooltipOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, tooltipOffset, 0);
}

static addIcon(builder:flatbuffers.Builder, icon:number) {
  builder.addFieldInt32(3, icon, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, positionOffset, 0);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(5, radius, 0.0);
}

static addMapId(builder:flatbuffers.Builder, mapId:number) {
  builder.addFieldInt32(6, mapId, 0);
}

static addDataId(builder:flatbuffers.Builder, dataId:number) {
  builder.addFieldInt32(7, dataId, 0);
}

static endDynamicMarkerData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 12) // position
  return offset;
}

}
