// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Location {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Location {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLocation(bb:flatbuffers.ByteBuffer, obj?:Location):Location {
  return (obj || new Location()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLocation(bb:flatbuffers.ByteBuffer, obj?:Location):Location {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Location()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mapId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startLocation(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMapId(builder:flatbuffers.Builder, mapId:number) {
  builder.addFieldInt32(0, mapId, 0);
}

static endLocation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLocation(builder:flatbuffers.Builder, mapId:number):flatbuffers.Offset {
  Location.startLocation(builder);
  Location.addMapId(builder, mapId);
  return Location.endLocation(builder);
}
}
