// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Map } from './map.js';
import { MapMarkersPair } from './map-markers-pair.js';
import { MarkerName } from './marker-name.js';


export class MapData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MapData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapData(bb:flatbuffers.ByteBuffer, obj?:MapData):MapData {
  return (obj || new MapData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapData(bb:flatbuffers.ByteBuffer, obj?:MapData):MapData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

maps(index: number, obj?:Map):Map|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Map()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

mapsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

markers(index: number, obj?:MapMarkersPair):MapMarkersPair|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new MapMarkersPair()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

markersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

markerNames(index: number, obj?:MarkerName):MarkerName|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new MarkerName()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

markerNamesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMapData(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addMaps(builder:flatbuffers.Builder, mapsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, mapsOffset, 0);
}

static createMapsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMapsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMarkers(builder:flatbuffers.Builder, markersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, markersOffset, 0);
}

static createMarkersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMarkersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMarkerNames(builder:flatbuffers.Builder, markerNamesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, markerNamesOffset, 0);
}

static createMarkerNamesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMarkerNamesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMapData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMapData(builder:flatbuffers.Builder, mapsOffset:flatbuffers.Offset, markersOffset:flatbuffers.Offset, markerNamesOffset:flatbuffers.Offset):flatbuffers.Offset {
  MapData.startMapData(builder);
  MapData.addMaps(builder, mapsOffset);
  MapData.addMarkers(builder, markersOffset);
  MapData.addMarkerNames(builder, markerNamesOffset);
  return MapData.endMapData(builder);
}
}
