// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class MapLinkData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MapLinkData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapLinkData(bb:flatbuffers.ByteBuffer, obj?:MapLinkData):MapLinkData {
  return (obj || new MapLinkData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapLinkData(bb:flatbuffers.ByteBuffer, obj?:MapLinkData):MapLinkData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapLinkData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

targetMapId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startMapLinkData(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTargetMapId(builder:flatbuffers.Builder, targetMapId:number) {
  builder.addFieldInt32(0, targetMapId, 0);
}

static endMapLinkData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMapLinkData(builder:flatbuffers.Builder, targetMapId:number):flatbuffers.Offset {
  MapLinkData.startMapLinkData(builder);
  MapLinkData.addTargetMapId(builder, targetMapId);
  return MapLinkData.endMapLinkData(builder);
}
}
