// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StaticMarker } from './static-marker.js';


export class MapMarkersPair {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MapMarkersPair {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapMarkersPair(bb:flatbuffers.ByteBuffer, obj?:MapMarkersPair):MapMarkersPair {
  return (obj || new MapMarkersPair()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapMarkersPair(bb:flatbuffers.ByteBuffer, obj?:MapMarkersPair):MapMarkersPair {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapMarkersPair()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

value(index: number, obj?:StaticMarker):StaticMarker|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new StaticMarker()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

valueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMapMarkersPair(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, key:number) {
  builder.addFieldInt32(0, key, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static createValueVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMapMarkersPair(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMapMarkersPair(builder:flatbuffers.Builder, key:number, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  MapMarkersPair.startMapMarkersPair(builder);
  MapMarkersPair.addKey(builder, key);
  MapMarkersPair.addValue(builder, valueOffset);
  return MapMarkersPair.endMapMarkersPair(builder);
}
}
