// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Map {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Map {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMap(bb:flatbuffers.ByteBuffer, obj?:Map):Map {
  return (obj || new Map()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMap(bb:flatbuffers.ByteBuffer, obj?:Map):Map {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Map()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rowId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

region():string|null
region(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
region(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

place():string|null
place(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
place(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

subPlace():string|null
subPlace(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
subPlace(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mapMarkerRange():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

priorityCategoryUi():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

priorityUi():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

hierarchy():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

discoveryArrayByte():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

discoveryFlag():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

discoveryIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

sizeFactor():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

offsetX():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

offsetY():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startMap(builder:flatbuffers.Builder) {
  builder.startObject(15);
}

static addRowId(builder:flatbuffers.Builder, rowId:number) {
  builder.addFieldInt32(0, rowId, 0);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, idOffset, 0);
}

static addRegion(builder:flatbuffers.Builder, regionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, regionOffset, 0);
}

static addPlace(builder:flatbuffers.Builder, placeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, placeOffset, 0);
}

static addSubPlace(builder:flatbuffers.Builder, subPlaceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, subPlaceOffset, 0);
}

static addMapMarkerRange(builder:flatbuffers.Builder, mapMarkerRange:number) {
  builder.addFieldInt16(5, mapMarkerRange, 0);
}

static addPriorityCategoryUi(builder:flatbuffers.Builder, priorityCategoryUi:number) {
  builder.addFieldInt32(6, priorityCategoryUi, 0);
}

static addPriorityUi(builder:flatbuffers.Builder, priorityUi:number) {
  builder.addFieldInt32(7, priorityUi, 0);
}

static addHierarchy(builder:flatbuffers.Builder, hierarchy:number) {
  builder.addFieldInt32(8, hierarchy, 0);
}

static addDiscoveryArrayByte(builder:flatbuffers.Builder, discoveryArrayByte:boolean) {
  builder.addFieldInt8(9, +discoveryArrayByte, +false);
}

static addDiscoveryFlag(builder:flatbuffers.Builder, discoveryFlag:number) {
  builder.addFieldInt32(10, discoveryFlag, 0);
}

static addDiscoveryIndex(builder:flatbuffers.Builder, discoveryIndex:number) {
  builder.addFieldInt16(11, discoveryIndex, 0);
}

static addSizeFactor(builder:flatbuffers.Builder, sizeFactor:number) {
  builder.addFieldInt16(12, sizeFactor, 0);
}

static addOffsetX(builder:flatbuffers.Builder, offsetX:number) {
  builder.addFieldInt16(13, offsetX, 0);
}

static addOffsetY(builder:flatbuffers.Builder, offsetY:number) {
  builder.addFieldInt16(14, offsetY, 0);
}

static endMap(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // id
  builder.requiredField(offset, 8) // region
  builder.requiredField(offset, 10) // place
  return offset;
}

static createMap(builder:flatbuffers.Builder, rowId:number, idOffset:flatbuffers.Offset, regionOffset:flatbuffers.Offset, placeOffset:flatbuffers.Offset, subPlaceOffset:flatbuffers.Offset, mapMarkerRange:number, priorityCategoryUi:number, priorityUi:number, hierarchy:number, discoveryArrayByte:boolean, discoveryFlag:number, discoveryIndex:number, sizeFactor:number, offsetX:number, offsetY:number):flatbuffers.Offset {
  Map.startMap(builder);
  Map.addRowId(builder, rowId);
  Map.addId(builder, idOffset);
  Map.addRegion(builder, regionOffset);
  Map.addPlace(builder, placeOffset);
  Map.addSubPlace(builder, subPlaceOffset);
  Map.addMapMarkerRange(builder, mapMarkerRange);
  Map.addPriorityCategoryUi(builder, priorityCategoryUi);
  Map.addPriorityUi(builder, priorityUi);
  Map.addHierarchy(builder, hierarchy);
  Map.addDiscoveryArrayByte(builder, discoveryArrayByte);
  Map.addDiscoveryFlag(builder, discoveryFlag);
  Map.addDiscoveryIndex(builder, discoveryIndex);
  Map.addSizeFactor(builder, sizeFactor);
  Map.addOffsetX(builder, offsetX);
  Map.addOffsetY(builder, offsetY);
  return Map.endMap(builder);
}
}
