// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { DiscoveryMask } from './discovery-mask.js';
import { DynamicMarker } from './dynamic-marker.js';
import { DynamicMarkerList } from './dynamic-marker-list.js';
import { FlagMarkerList } from './flag-marker-list.js';
import { Location } from './location.js';
import { MapData } from './map-data.js';
import { PlayerTransformAndCameraRotation } from './player-transform-and-camera-rotation.js';
import { QuestLinkMarkerList } from './quest-link-marker-list.js';
import { SelectedLocation } from './selected-location.js';


export enum MessagePayload {
  NONE = 0,
  MapData = 1,
  Location = 2,
  PlayerTransformAndCameraRotation = 3,
  SelectedLocation = 4,
  DiscoveryMask = 5,
  DynamicMarker = 6,
  DynamicMarkerList = 7,
  QuestLinkMarkerList = 8,
  FlagMarkerList = 9
}

export function unionToMessagePayload(
  type: MessagePayload,
  accessor: (obj:DiscoveryMask|DynamicMarker|DynamicMarkerList|FlagMarkerList|Location|MapData|PlayerTransformAndCameraRotation|QuestLinkMarkerList|SelectedLocation) => DiscoveryMask|DynamicMarker|DynamicMarkerList|FlagMarkerList|Location|MapData|PlayerTransformAndCameraRotation|QuestLinkMarkerList|SelectedLocation|null
): DiscoveryMask|DynamicMarker|DynamicMarkerList|FlagMarkerList|Location|MapData|PlayerTransformAndCameraRotation|QuestLinkMarkerList|SelectedLocation|null {
  switch(MessagePayload[type]) {
    case 'NONE': return null; 
    case 'MapData': return accessor(new MapData())! as MapData;
    case 'Location': return accessor(new Location())! as Location;
    case 'PlayerTransformAndCameraRotation': return accessor(new PlayerTransformAndCameraRotation())! as PlayerTransformAndCameraRotation;
    case 'SelectedLocation': return accessor(new SelectedLocation())! as SelectedLocation;
    case 'DiscoveryMask': return accessor(new DiscoveryMask())! as DiscoveryMask;
    case 'DynamicMarker': return accessor(new DynamicMarker())! as DynamicMarker;
    case 'DynamicMarkerList': return accessor(new DynamicMarkerList())! as DynamicMarkerList;
    case 'QuestLinkMarkerList': return accessor(new QuestLinkMarkerList())! as QuestLinkMarkerList;
    case 'FlagMarkerList': return accessor(new FlagMarkerList())! as FlagMarkerList;
    default: return null;
  }
}

export function unionListToMessagePayload(
  type: MessagePayload, 
  accessor: (index: number, obj:DiscoveryMask|DynamicMarker|DynamicMarkerList|FlagMarkerList|Location|MapData|PlayerTransformAndCameraRotation|QuestLinkMarkerList|SelectedLocation) => DiscoveryMask|DynamicMarker|DynamicMarkerList|FlagMarkerList|Location|MapData|PlayerTransformAndCameraRotation|QuestLinkMarkerList|SelectedLocation|null, 
  index: number
): DiscoveryMask|DynamicMarker|DynamicMarkerList|FlagMarkerList|Location|MapData|PlayerTransformAndCameraRotation|QuestLinkMarkerList|SelectedLocation|null {
  switch(MessagePayload[type]) {
    case 'NONE': return null; 
    case 'MapData': return accessor(index, new MapData())! as MapData;
    case 'Location': return accessor(index, new Location())! as Location;
    case 'PlayerTransformAndCameraRotation': return accessor(index, new PlayerTransformAndCameraRotation())! as PlayerTransformAndCameraRotation;
    case 'SelectedLocation': return accessor(index, new SelectedLocation())! as SelectedLocation;
    case 'DiscoveryMask': return accessor(index, new DiscoveryMask())! as DiscoveryMask;
    case 'DynamicMarker': return accessor(index, new DynamicMarker())! as DynamicMarker;
    case 'DynamicMarkerList': return accessor(index, new DynamicMarkerList())! as DynamicMarkerList;
    case 'QuestLinkMarkerList': return accessor(index, new QuestLinkMarkerList())! as QuestLinkMarkerList;
    case 'FlagMarkerList': return accessor(index, new FlagMarkerList())! as FlagMarkerList;
    default: return null;
  }
}
