// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SeString } from './se-string.js';


export class PlaceNameData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlaceNameData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlaceNameData(bb:flatbuffers.ByteBuffer, obj?:PlaceNameData):PlaceNameData {
  return (obj || new PlaceNameData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlaceNameData(bb:flatbuffers.ByteBuffer, obj?:PlaceNameData):PlaceNameData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlaceNameData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tooltip(obj?:SeString):SeString|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SeString()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startPlaceNameData(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTooltip(builder:flatbuffers.Builder, tooltipOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tooltipOffset, 0);
}

static endPlaceNameData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // tooltip
  return offset;
}

static createPlaceNameData(builder:flatbuffers.Builder, tooltipOffset:flatbuffers.Offset):flatbuffers.Offset {
  PlaceNameData.startPlaceNameData(builder);
  PlaceNameData.addTooltip(builder, tooltipOffset);
  return PlaceNameData.endPlaceNameData(builder);
}
}
