// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Transform } from './transform.js';


export class PlayerTransformAndCameraRotation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerTransformAndCameraRotation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerTransformAndCameraRotation(bb:flatbuffers.ByteBuffer, obj?:PlayerTransformAndCameraRotation):PlayerTransformAndCameraRotation {
  return (obj || new PlayerTransformAndCameraRotation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerTransformAndCameraRotation(bb:flatbuffers.ByteBuffer, obj?:PlayerTransformAndCameraRotation):PlayerTransformAndCameraRotation {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerTransformAndCameraRotation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

playerTransform(obj?:Transform):Transform|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Transform()).__init(this.bb_pos + offset, this.bb!) : null;
}

cameraRotation():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startPlayerTransformAndCameraRotation(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPlayerTransform(builder:flatbuffers.Builder, playerTransformOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, playerTransformOffset, 0);
}

static addCameraRotation(builder:flatbuffers.Builder, cameraRotation:number) {
  builder.addFieldFloat32(1, cameraRotation, 0.0);
}

static endPlayerTransformAndCameraRotation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerTransformAndCameraRotation(builder:flatbuffers.Builder, playerTransformOffset:flatbuffers.Offset, cameraRotation:number):flatbuffers.Offset {
  PlayerTransformAndCameraRotation.startPlayerTransformAndCameraRotation(builder);
  PlayerTransformAndCameraRotation.addPlayerTransform(builder, playerTransformOffset);
  PlayerTransformAndCameraRotation.addCameraRotation(builder, cameraRotation);
  return PlayerTransformAndCameraRotation.endPlayerTransformAndCameraRotation(builder);
}
}
