// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vector3 } from './vector3.js';


export class QuestLinkMarker {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):QuestLinkMarker {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQuestLinkMarker(bb:flatbuffers.ByteBuffer, obj?:QuestLinkMarker):QuestLinkMarker {
  return (obj || new QuestLinkMarker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQuestLinkMarker(bb:flatbuffers.ByteBuffer, obj?:QuestLinkMarker):QuestLinkMarker {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QuestLinkMarker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

icon():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

tooltip():string|null
tooltip(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
tooltip(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

levelId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

position(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

recommendedLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

sourceMapId():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

targetMapId():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startQuestLinkMarker(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addIcon(builder:flatbuffers.Builder, icon:number) {
  builder.addFieldInt32(0, icon, 0);
}

static addTooltip(builder:flatbuffers.Builder, tooltipOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, tooltipOffset, 0);
}

static addLevelId(builder:flatbuffers.Builder, levelId:number) {
  builder.addFieldInt32(2, levelId, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, positionOffset, 0);
}

static addRecommendedLevel(builder:flatbuffers.Builder, recommendedLevel:number) {
  builder.addFieldInt16(4, recommendedLevel, 0);
}

static addSourceMapId(builder:flatbuffers.Builder, sourceMapId:number) {
  builder.addFieldInt32(5, sourceMapId, 0);
}

static addTargetMapId(builder:flatbuffers.Builder, targetMapId:number) {
  builder.addFieldInt32(6, targetMapId, 0);
}

static endQuestLinkMarker(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 10) // position
  return offset;
}

}
