// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { QuestLinkMarker } from './quest-link-marker.js';


export class QuestLinkMarkerList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):QuestLinkMarkerList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQuestLinkMarkerList(bb:flatbuffers.ByteBuffer, obj?:QuestLinkMarkerList):QuestLinkMarkerList {
  return (obj || new QuestLinkMarkerList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQuestLinkMarkerList(bb:flatbuffers.ByteBuffer, obj?:QuestLinkMarkerList):QuestLinkMarkerList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QuestLinkMarkerList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

markers(index: number, obj?:QuestLinkMarker):QuestLinkMarker|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new QuestLinkMarker()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

markersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startQuestLinkMarkerList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMarkers(builder:flatbuffers.Builder, markersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, markersOffset, 0);
}

static createMarkersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMarkersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endQuestLinkMarkerList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createQuestLinkMarkerList(builder:flatbuffers.Builder, markersOffset:flatbuffers.Offset):flatbuffers.Offset {
  QuestLinkMarkerList.startQuestLinkMarkerList(builder);
  QuestLinkMarkerList.addMarkers(builder, markersOffset);
  return QuestLinkMarkerList.endQuestLinkMarkerList(builder);
}
}
