// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SelectedLocation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SelectedLocation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSelectedLocation(bb:flatbuffers.ByteBuffer, obj?:SelectedLocation):SelectedLocation {
  return (obj || new SelectedLocation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSelectedLocation(bb:flatbuffers.ByteBuffer, obj?:SelectedLocation):SelectedLocation {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SelectedLocation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mapId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

discoveryMask():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startSelectedLocation(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMapId(builder:flatbuffers.Builder, mapId:number) {
  builder.addFieldInt32(0, mapId, 0);
}

static addDiscoveryMask(builder:flatbuffers.Builder, discoveryMask:number) {
  builder.addFieldInt32(1, discoveryMask, 0);
}

static endSelectedLocation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSelectedLocation(builder:flatbuffers.Builder, mapId:number, discoveryMask:number):flatbuffers.Offset {
  SelectedLocation.startSelectedLocation(builder);
  SelectedLocation.addMapId(builder, mapId);
  SelectedLocation.addDiscoveryMask(builder, discoveryMask);
  return SelectedLocation.endSelectedLocation(builder);
}
}
