// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MessagePayload, unionToMessagePayload, unionListToMessagePayload } from './message-payload.js';
import { MessageType } from './message-type.js';


export class ServerMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsServerMessage(bb:flatbuffers.ByteBuffer, obj?:ServerMessage):ServerMessage {
  return (obj || new ServerMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsServerMessage(bb:flatbuffers.ByteBuffer, obj?:ServerMessage):ServerMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():MessageType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MessageType.MapData;
}

payloadType():MessagePayload {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MessagePayload.NONE;
}

payload<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startServerMessage(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addType(builder:flatbuffers.Builder, type:MessageType) {
  builder.addFieldInt8(0, type, MessageType.MapData);
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:MessagePayload) {
  builder.addFieldInt8(1, payloadType, MessagePayload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
}

static endServerMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishServerMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedServerMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createServerMessage(builder:flatbuffers.Builder, type:MessageType, payloadType:MessagePayload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  ServerMessage.startServerMessage(builder);
  ServerMessage.addType(builder, type);
  ServerMessage.addPayloadType(builder, payloadType);
  ServerMessage.addPayload(builder, payloadOffset);
  return ServerMessage.endServerMessage(builder);
}
}
