// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SeString } from './se-string.js';
import { StaticMarkerData, unionToStaticMarkerData, unionListToStaticMarkerData } from './static-marker-data.js';
import { Vector2 } from './vector2.js';


export class StaticMarker {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StaticMarker {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStaticMarker(bb:flatbuffers.ByteBuffer, obj?:StaticMarker):StaticMarker {
  return (obj || new StaticMarker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStaticMarker(bb:flatbuffers.ByteBuffer, obj?:StaticMarker):StaticMarker {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StaticMarker()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

subRowId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

title(obj?:SeString):SeString|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new SeString()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

icon():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : null;
}

position(obj?:Vector2):Vector2|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vector2()).__init(this.bb_pos + offset, this.bb!) : null;
}

subtextOrientation():number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : null;
}

type():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

dataType():StaticMarkerData {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StaticMarkerData.NONE;
}

data<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startStaticMarker(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addSubRowId(builder:flatbuffers.Builder, subRowId:number) {
  builder.addFieldInt32(0, subRowId, 0);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, titleOffset, 0);
}

static addIcon(builder:flatbuffers.Builder, icon:number) {
  builder.addFieldInt16(2, icon, null);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, positionOffset, 0);
}

static addSubtextOrientation(builder:flatbuffers.Builder, subtextOrientation:number) {
  builder.addFieldInt8(4, subtextOrientation, null);
}

static addType(builder:flatbuffers.Builder, type:number) {
  builder.addFieldInt8(5, type, 0);
}

static addDataType(builder:flatbuffers.Builder, dataType:StaticMarkerData) {
  builder.addFieldInt8(6, dataType, StaticMarkerData.NONE);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, dataOffset, 0);
}

static endStaticMarker(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 10) // position
  return offset;
}

}
