// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { AetheryteData } from './aetheryte-data.js';
import { MapLinkData } from './map-link-data.js';
import { PlaceNameData } from './place-name-data.js';


export enum StaticMarkerData {
  NONE = 0,
  MapLink = 1,
  ImplicitMapLink = 2,
  Aetheryte = 3,
  PlaceName = 4
}

export function unionToStaticMarkerData(
  type: StaticMarkerData,
  accessor: (obj:AetheryteData|MapLinkData|PlaceNameData) => AetheryteData|MapLinkData|PlaceNameData|null
): AetheryteData|MapLinkData|PlaceNameData|null {
  switch(StaticMarkerData[type]) {
    case 'NONE': return null; 
    case 'MapLink': return accessor(new MapLinkData())! as MapLinkData;
    case 'ImplicitMapLink': return accessor(new MapLinkData())! as MapLinkData;
    case 'Aetheryte': return accessor(new AetheryteData())! as AetheryteData;
    case 'PlaceName': return accessor(new PlaceNameData())! as PlaceNameData;
    default: return null;
  }
}

export function unionListToStaticMarkerData(
  type: StaticMarkerData, 
  accessor: (index: number, obj:AetheryteData|MapLinkData|PlaceNameData) => AetheryteData|MapLinkData|PlaceNameData|null, 
  index: number
): AetheryteData|MapLinkData|PlaceNameData|null {
  switch(StaticMarkerData[type]) {
    case 'NONE': return null; 
    case 'MapLink': return accessor(index, new MapLinkData())! as MapLinkData;
    case 'ImplicitMapLink': return accessor(index, new MapLinkData())! as MapLinkData;
    case 'Aetheryte': return accessor(index, new AetheryteData())! as AetheryteData;
    case 'PlaceName': return accessor(index, new PlaceNameData())! as PlaceNameData;
    default: return null;
  }
}
