// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AetheryteData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AetheryteData GetRootAsAetheryteData(ByteBuffer _bb) { return GetRootAsAetheryteData(_bb, new AetheryteData()); }
  public static AetheryteData GetRootAsAetheryteData(ByteBuffer _bb, AetheryteData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AetheryteData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint AetheryteId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<WebMap.Networking.Models.AetheryteData> CreateAetheryteData(FlatBufferBuilder builder,
      uint aetheryte_id = 0) {
    builder.StartTable(1);
    AetheryteData.AddAetheryteId(builder, aetheryte_id);
    return AetheryteData.EndAetheryteData(builder);
  }

  public static void StartAetheryteData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddAetheryteId(FlatBufferBuilder builder, uint aetheryteId) { builder.AddUint(0, aetheryteId, 0); }
  public static Offset<WebMap.Networking.Models.AetheryteData> EndAetheryteData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.AetheryteData>(o);
  }
}


static public class AetheryteDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*AetheryteId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
