// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DiscoveryMask : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DiscoveryMask GetRootAsDiscoveryMask(ByteBuffer _bb) { return GetRootAsDiscoveryMask(_bb, new DiscoveryMask()); }
  public static DiscoveryMask GetRootAsDiscoveryMask(ByteBuffer _bb, DiscoveryMask obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DiscoveryMask __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Mask { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WebMap.Networking.Models.DiscoveryMask> CreateDiscoveryMask(FlatBufferBuilder builder,
      int mask = 0) {
    builder.StartTable(1);
    DiscoveryMask.AddMask(builder, mask);
    return DiscoveryMask.EndDiscoveryMask(builder);
  }

  public static void StartDiscoveryMask(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMask(FlatBufferBuilder builder, int mask) { builder.AddInt(0, mask, 0); }
  public static Offset<WebMap.Networking.Models.DiscoveryMask> EndDiscoveryMask(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.DiscoveryMask>(o);
  }
}


static public class DiscoveryMaskVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Mask*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
