// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DynamicMarker : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DynamicMarker GetRootAsDynamicMarker(ByteBuffer _bb) { return GetRootAsDynamicMarker(_bb, new DynamicMarker()); }
  public static DynamicMarker GetRootAsDynamicMarker(ByteBuffer _bb, DynamicMarker obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DynamicMarker __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint ObjectiveId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Label { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLabelBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetLabelBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetLabelArray() { return __p.__vector_as_array<byte>(6); }
  public WebMap.Networking.Models.DynamicMarkerData? Data(int j) { int o = __p.__offset(8); return o != 0 ? (WebMap.Networking.Models.DynamicMarkerData?)(new WebMap.Networking.Models.DynamicMarkerData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ushort RecommendedLevel { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public bool ShouldRender { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<WebMap.Networking.Models.DynamicMarker> CreateDynamicMarker(FlatBufferBuilder builder,
      uint objective_id = 0,
      StringOffset labelOffset = default(StringOffset),
      VectorOffset dataOffset = default(VectorOffset),
      ushort recommended_level = 0,
      bool should_render = false) {
    builder.StartTable(5);
    DynamicMarker.AddData(builder, dataOffset);
    DynamicMarker.AddLabel(builder, labelOffset);
    DynamicMarker.AddObjectiveId(builder, objective_id);
    DynamicMarker.AddRecommendedLevel(builder, recommended_level);
    DynamicMarker.AddShouldRender(builder, should_render);
    return DynamicMarker.EndDynamicMarker(builder);
  }

  public static void StartDynamicMarker(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddObjectiveId(FlatBufferBuilder builder, uint objectiveId) { builder.AddUint(0, objectiveId, 0); }
  public static void AddLabel(FlatBufferBuilder builder, StringOffset labelOffset) { builder.AddOffset(1, labelOffset.Value, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(2, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.DynamicMarkerData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.DynamicMarkerData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<WebMap.Networking.Models.DynamicMarkerData>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<WebMap.Networking.Models.DynamicMarkerData>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRecommendedLevel(FlatBufferBuilder builder, ushort recommendedLevel) { builder.AddUshort(3, recommendedLevel, 0); }
  public static void AddShouldRender(FlatBufferBuilder builder, bool shouldRender) { builder.AddBool(4, shouldRender, false); }
  public static Offset<WebMap.Networking.Models.DynamicMarker> EndDynamicMarker(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.DynamicMarker>(o);
  }
}


static public class DynamicMarkerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ObjectiveId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Label*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Data*/, WebMap.Networking.Models.DynamicMarkerDataVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*RecommendedLevel*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 12 /*ShouldRender*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
