// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DynamicMarkerData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DynamicMarkerData GetRootAsDynamicMarkerData(ByteBuffer _bb) { return GetRootAsDynamicMarkerData(_bb, new DynamicMarkerData()); }
  public static DynamicMarkerData GetRootAsDynamicMarkerData(ByteBuffer _bb, DynamicMarkerData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DynamicMarkerData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint LevelId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ObjectiveId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Tooltip { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTooltipBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTooltipBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTooltipArray() { return __p.__vector_as_array<byte>(8); }
  public uint Icon { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public WebMap.Networking.Models.Vector3? Position { get { int o = __p.__offset(12); return o != 0 ? (WebMap.Networking.Models.Vector3?)(new WebMap.Networking.Models.Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Radius { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public uint MapId { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint DataId { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static void StartDynamicMarkerData(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddLevelId(FlatBufferBuilder builder, uint levelId) { builder.AddUint(0, levelId, 0); }
  public static void AddObjectiveId(FlatBufferBuilder builder, uint objectiveId) { builder.AddUint(1, objectiveId, 0); }
  public static void AddTooltip(FlatBufferBuilder builder, StringOffset tooltipOffset) { builder.AddOffset(2, tooltipOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, uint icon) { builder.AddUint(3, icon, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.Vector3> positionOffset) { builder.AddStruct(4, positionOffset.Value, 0); }
  public static void AddRadius(FlatBufferBuilder builder, float radius) { builder.AddFloat(5, radius, 0.0f); }
  public static void AddMapId(FlatBufferBuilder builder, uint mapId) { builder.AddUint(6, mapId, 0); }
  public static void AddDataId(FlatBufferBuilder builder, uint dataId) { builder.AddUint(7, dataId, 0); }
  public static Offset<WebMap.Networking.Models.DynamicMarkerData> EndDynamicMarkerData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 12);  // position
    return new Offset<WebMap.Networking.Models.DynamicMarkerData>(o);
  }
}


static public class DynamicMarkerDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*LevelId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*ObjectiveId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*Tooltip*/, false)
      && verifier.VerifyField(tablePos, 10 /*Icon*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Position*/, 12 /*WebMap.Networking.Models.Vector3*/, 4, true)
      && verifier.VerifyField(tablePos, 14 /*Radius*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*MapId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*DataId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
