// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FlagMarker : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FlagMarker GetRootAsFlagMarker(ByteBuffer _bb) { return GetRootAsFlagMarker(_bb, new FlagMarker()); }
  public static FlagMarker GetRootAsFlagMarker(ByteBuffer _bb, FlagMarker obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FlagMarker __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartFlagMarker(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<WebMap.Networking.Models.FlagMarker> EndFlagMarker(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.FlagMarker>(o);
  }
}


static public class FlagMarkerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
