// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Location : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Location GetRootAsLocation(ByteBuffer _bb) { return GetRootAsLocation(_bb, new Location()); }
  public static Location GetRootAsLocation(ByteBuffer _bb, Location obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Location __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint MapId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<WebMap.Networking.Models.Location> CreateLocation(FlatBufferBuilder builder,
      uint map_id = 0) {
    builder.StartTable(1);
    Location.AddMapId(builder, map_id);
    return Location.EndLocation(builder);
  }

  public static void StartLocation(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMapId(FlatBufferBuilder builder, uint mapId) { builder.AddUint(0, mapId, 0); }
  public static Offset<WebMap.Networking.Models.Location> EndLocation(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.Location>(o);
  }
}


static public class LocationVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MapId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
