// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MapData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MapData GetRootAsMapData(ByteBuffer _bb) { return GetRootAsMapData(_bb, new MapData()); }
  public static MapData GetRootAsMapData(ByteBuffer _bb, MapData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MapData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public WebMap.Networking.Models.Map? Maps(int j) { int o = __p.__offset(4); return o != 0 ? (WebMap.Networking.Models.Map?)(new WebMap.Networking.Models.Map()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MapsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public WebMap.Networking.Models.Map? MapsByKey(uint key) { int o = __p.__offset(4); return o != 0 ? WebMap.Networking.Models.Map.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public WebMap.Networking.Models.MapMarkersPair? Markers(int j) { int o = __p.__offset(6); return o != 0 ? (WebMap.Networking.Models.MapMarkersPair?)(new WebMap.Networking.Models.MapMarkersPair()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MarkersLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public WebMap.Networking.Models.MapMarkersPair? MarkersByKey(uint key) { int o = __p.__offset(6); return o != 0 ? WebMap.Networking.Models.MapMarkersPair.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public WebMap.Networking.Models.MarkerName? MarkerNames(int j) { int o = __p.__offset(8); return o != 0 ? (WebMap.Networking.Models.MarkerName?)(new WebMap.Networking.Models.MarkerName()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MarkerNamesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public WebMap.Networking.Models.MarkerName? MarkerNamesByKey(uint key) { int o = __p.__offset(8); return o != 0 ? WebMap.Networking.Models.MarkerName.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<WebMap.Networking.Models.MapData> CreateMapData(FlatBufferBuilder builder,
      VectorOffset mapsOffset = default(VectorOffset),
      VectorOffset markersOffset = default(VectorOffset),
      VectorOffset marker_namesOffset = default(VectorOffset)) {
    builder.StartTable(3);
    MapData.AddMarkerNames(builder, marker_namesOffset);
    MapData.AddMarkers(builder, markersOffset);
    MapData.AddMaps(builder, mapsOffset);
    return MapData.EndMapData(builder);
  }

  public static void StartMapData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddMaps(FlatBufferBuilder builder, VectorOffset mapsOffset) { builder.AddOffset(0, mapsOffset.Value, 0); }
  public static VectorOffset CreateMapsVector(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.Map>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMapsVectorBlock(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.Map>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMapsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<WebMap.Networking.Models.Map>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMapsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<WebMap.Networking.Models.Map>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMapsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMarkers(FlatBufferBuilder builder, VectorOffset markersOffset) { builder.AddOffset(1, markersOffset.Value, 0); }
  public static VectorOffset CreateMarkersVector(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.MapMarkersPair>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMarkersVectorBlock(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.MapMarkersPair>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMarkersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<WebMap.Networking.Models.MapMarkersPair>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMarkersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<WebMap.Networking.Models.MapMarkersPair>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMarkersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMarkerNames(FlatBufferBuilder builder, VectorOffset markerNamesOffset) { builder.AddOffset(2, markerNamesOffset.Value, 0); }
  public static VectorOffset CreateMarkerNamesVector(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.MarkerName>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMarkerNamesVectorBlock(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.MarkerName>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMarkerNamesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<WebMap.Networking.Models.MarkerName>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMarkerNamesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<WebMap.Networking.Models.MarkerName>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMarkerNamesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<WebMap.Networking.Models.MapData> EndMapData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.MapData>(o);
  }
}


static public class MapDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Maps*/, WebMap.Networking.Models.MapVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Markers*/, WebMap.Networking.Models.MapMarkersPairVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*MarkerNames*/, WebMap.Networking.Models.MarkerNameVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
