// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MapLinkData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MapLinkData GetRootAsMapLinkData(ByteBuffer _bb) { return GetRootAsMapLinkData(_bb, new MapLinkData()); }
  public static MapLinkData GetRootAsMapLinkData(ByteBuffer _bb, MapLinkData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MapLinkData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint TargetMapId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<WebMap.Networking.Models.MapLinkData> CreateMapLinkData(FlatBufferBuilder builder,
      uint target_map_id = 0) {
    builder.StartTable(1);
    MapLinkData.AddTargetMapId(builder, target_map_id);
    return MapLinkData.EndMapLinkData(builder);
  }

  public static void StartMapLinkData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTargetMapId(FlatBufferBuilder builder, uint targetMapId) { builder.AddUint(0, targetMapId, 0); }
  public static Offset<WebMap.Networking.Models.MapLinkData> EndMapLinkData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.MapLinkData>(o);
  }
}


static public class MapLinkDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TargetMapId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
