// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MapMarkersPair : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MapMarkersPair GetRootAsMapMarkersPair(ByteBuffer _bb) { return GetRootAsMapMarkersPair(_bb, new MapMarkersPair()); }
  public static MapMarkersPair GetRootAsMapMarkersPair(ByteBuffer _bb, MapMarkersPair obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MapMarkersPair __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Key { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public WebMap.Networking.Models.StaticMarker? Value(int j) { int o = __p.__offset(6); return o != 0 ? (WebMap.Networking.Models.StaticMarker?)(new WebMap.Networking.Models.StaticMarker()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ValueLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public WebMap.Networking.Models.StaticMarker? ValueByKey(uint key) { int o = __p.__offset(6); return o != 0 ? WebMap.Networking.Models.StaticMarker.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<WebMap.Networking.Models.MapMarkersPair> CreateMapMarkersPair(FlatBufferBuilder builder,
      uint key = 0,
      VectorOffset valueOffset = default(VectorOffset)) {
    builder.StartTable(2);
    MapMarkersPair.AddValue(builder, valueOffset);
    MapMarkersPair.AddKey(builder, key);
    return MapMarkersPair.EndMapMarkersPair(builder);
  }

  public static void StartMapMarkersPair(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKey(FlatBufferBuilder builder, uint key) { builder.AddUint(0, key, 0); }
  public static void AddValue(FlatBufferBuilder builder, VectorOffset valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
  public static VectorOffset CreateValueVector(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.StaticMarker>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateValueVectorBlock(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.StaticMarker>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValueVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<WebMap.Networking.Models.StaticMarker>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValueVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<WebMap.Networking.Models.StaticMarker>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartValueVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<WebMap.Networking.Models.MapMarkersPair> EndMapMarkersPair(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.MapMarkersPair>(o);
  }

  public static VectorOffset CreateSortedVectorOfMapMarkersPair(FlatBufferBuilder builder, Offset<MapMarkersPair>[] offsets) {
    Array.Sort(offsets,
      (Offset<MapMarkersPair> o1, Offset<MapMarkersPair> o2) =>
        new MapMarkersPair().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).Key.CompareTo(new MapMarkersPair().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).Key));
    return builder.CreateVectorOfTables(offsets);
  }

  public static MapMarkersPair? __lookup_by_key(int vectorLocation, uint key, ByteBuffer bb) {
    MapMarkersPair obj_ = new MapMarkersPair();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_.Key.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
}


static public class MapMarkersPairVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Key*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Value*/, WebMap.Networking.Models.StaticMarkerVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
