// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MarkerName : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MarkerName GetRootAsMarkerName(ByteBuffer _bb) { return GetRootAsMarkerName(_bb, new MarkerName()); }
  public static MarkerName GetRootAsMarkerName(ByteBuffer _bb, MarkerName obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MarkerName __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<WebMap.Networking.Models.MarkerName> CreateMarkerName(FlatBufferBuilder builder,
      uint id = 0,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(2);
    MarkerName.AddName(builder, nameOffset);
    MarkerName.AddId(builder, id);
    return MarkerName.EndMarkerName(builder);
  }

  public static void StartMarkerName(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static Offset<WebMap.Networking.Models.MarkerName> EndMarkerName(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.MarkerName>(o);
  }

  public static VectorOffset CreateSortedVectorOfMarkerName(FlatBufferBuilder builder, Offset<MarkerName>[] offsets) {
    Array.Sort(offsets,
      (Offset<MarkerName> o1, Offset<MarkerName> o2) =>
        new MarkerName().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).Id.CompareTo(new MarkerName().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).Id));
    return builder.CreateVectorOfTables(offsets);
  }

  public static MarkerName? __lookup_by_key(int vectorLocation, uint key, ByteBuffer bb) {
    MarkerName obj_ = new MarkerName();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_.Id.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
}


static public class MarkerNameVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
