// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

public enum MessagePayload : byte
{
  NONE = 0,
  MapData = 1,
  Location = 2,
  PlayerTransformAndCameraRotation = 3,
  SelectedLocation = 4,
  DiscoveryMask = 5,
  DynamicMarker = 6,
  DynamicMarkerList = 7,
  QuestLinkMarkerList = 8,
  FlagMarkerList = 9,
};



static public class MessagePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((MessagePayload)typeId)
    {
      case MessagePayload.MapData:
        result = WebMap.Networking.Models.MapDataVerify.Verify(verifier, tablePos);
        break;
      case MessagePayload.Location:
        result = WebMap.Networking.Models.LocationVerify.Verify(verifier, tablePos);
        break;
      case MessagePayload.PlayerTransformAndCameraRotation:
        result = WebMap.Networking.Models.PlayerTransformAndCameraRotationVerify.Verify(verifier, tablePos);
        break;
      case MessagePayload.SelectedLocation:
        result = WebMap.Networking.Models.SelectedLocationVerify.Verify(verifier, tablePos);
        break;
      case MessagePayload.DiscoveryMask:
        result = WebMap.Networking.Models.DiscoveryMaskVerify.Verify(verifier, tablePos);
        break;
      case MessagePayload.DynamicMarker:
        result = WebMap.Networking.Models.DynamicMarkerVerify.Verify(verifier, tablePos);
        break;
      case MessagePayload.DynamicMarkerList:
        result = WebMap.Networking.Models.DynamicMarkerListVerify.Verify(verifier, tablePos);
        break;
      case MessagePayload.QuestLinkMarkerList:
        result = WebMap.Networking.Models.QuestLinkMarkerListVerify.Verify(verifier, tablePos);
        break;
      case MessagePayload.FlagMarkerList:
        result = WebMap.Networking.Models.FlagMarkerListVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
