// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlaceNameData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static PlaceNameData GetRootAsPlaceNameData(ByteBuffer _bb) { return GetRootAsPlaceNameData(_bb, new PlaceNameData()); }
  public static PlaceNameData GetRootAsPlaceNameData(ByteBuffer _bb, PlaceNameData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlaceNameData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public WebMap.Networking.Models.SeString? Tooltip { get { int o = __p.__offset(4); return o != 0 ? (WebMap.Networking.Models.SeString?)(new WebMap.Networking.Models.SeString()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<WebMap.Networking.Models.PlaceNameData> CreatePlaceNameData(FlatBufferBuilder builder,
      Offset<WebMap.Networking.Models.SeString> tooltipOffset = default(Offset<WebMap.Networking.Models.SeString>)) {
    builder.StartTable(1);
    PlaceNameData.AddTooltip(builder, tooltipOffset);
    return PlaceNameData.EndPlaceNameData(builder);
  }

  public static void StartPlaceNameData(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTooltip(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.SeString> tooltipOffset) { builder.AddOffset(0, tooltipOffset.Value, 0); }
  public static Offset<WebMap.Networking.Models.PlaceNameData> EndPlaceNameData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // tooltip
    return new Offset<WebMap.Networking.Models.PlaceNameData>(o);
  }
}


static public class PlaceNameDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Tooltip*/, WebMap.Networking.Models.SeStringVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
