// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerTransformAndCameraRotation : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static PlayerTransformAndCameraRotation GetRootAsPlayerTransformAndCameraRotation(ByteBuffer _bb) { return GetRootAsPlayerTransformAndCameraRotation(_bb, new PlayerTransformAndCameraRotation()); }
  public static PlayerTransformAndCameraRotation GetRootAsPlayerTransformAndCameraRotation(ByteBuffer _bb, PlayerTransformAndCameraRotation obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerTransformAndCameraRotation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public WebMap.Networking.Models.Transform? PlayerTransform { get { int o = __p.__offset(4); return o != 0 ? (WebMap.Networking.Models.Transform?)(new WebMap.Networking.Models.Transform()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float CameraRotation { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartPlayerTransformAndCameraRotation(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPlayerTransform(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.Transform> playerTransformOffset) { builder.AddStruct(0, playerTransformOffset.Value, 0); }
  public static void AddCameraRotation(FlatBufferBuilder builder, float cameraRotation) { builder.AddFloat(1, cameraRotation, 0.0f); }
  public static Offset<WebMap.Networking.Models.PlayerTransformAndCameraRotation> EndPlayerTransformAndCameraRotation(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.PlayerTransformAndCameraRotation>(o);
  }
}


static public class PlayerTransformAndCameraRotationVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PlayerTransform*/, 16 /*WebMap.Networking.Models.Transform*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*CameraRotation*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
