// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct QuestLinkMarkerList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static QuestLinkMarkerList GetRootAsQuestLinkMarkerList(ByteBuffer _bb) { return GetRootAsQuestLinkMarkerList(_bb, new QuestLinkMarkerList()); }
  public static QuestLinkMarkerList GetRootAsQuestLinkMarkerList(ByteBuffer _bb, QuestLinkMarkerList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public QuestLinkMarkerList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public WebMap.Networking.Models.QuestLinkMarker? Markers(int j) { int o = __p.__offset(4); return o != 0 ? (WebMap.Networking.Models.QuestLinkMarker?)(new WebMap.Networking.Models.QuestLinkMarker()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MarkersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<WebMap.Networking.Models.QuestLinkMarkerList> CreateQuestLinkMarkerList(FlatBufferBuilder builder,
      VectorOffset markersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    QuestLinkMarkerList.AddMarkers(builder, markersOffset);
    return QuestLinkMarkerList.EndQuestLinkMarkerList(builder);
  }

  public static void StartQuestLinkMarkerList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMarkers(FlatBufferBuilder builder, VectorOffset markersOffset) { builder.AddOffset(0, markersOffset.Value, 0); }
  public static VectorOffset CreateMarkersVector(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.QuestLinkMarker>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMarkersVectorBlock(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.QuestLinkMarker>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMarkersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<WebMap.Networking.Models.QuestLinkMarker>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMarkersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<WebMap.Networking.Models.QuestLinkMarker>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMarkersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<WebMap.Networking.Models.QuestLinkMarkerList> EndQuestLinkMarkerList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.QuestLinkMarkerList>(o);
  }
}


static public class QuestLinkMarkerListVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Markers*/, WebMap.Networking.Models.QuestLinkMarkerVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
