// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct QuestLinkMarker : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static QuestLinkMarker GetRootAsQuestLinkMarker(ByteBuffer _bb) { return GetRootAsQuestLinkMarker(_bb, new QuestLinkMarker()); }
  public static QuestLinkMarker GetRootAsQuestLinkMarker(ByteBuffer _bb, QuestLinkMarker obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public QuestLinkMarker __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Icon { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Tooltip { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTooltipBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTooltipBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTooltipArray() { return __p.__vector_as_array<byte>(6); }
  public uint LevelId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public WebMap.Networking.Models.Vector3? Position { get { int o = __p.__offset(10); return o != 0 ? (WebMap.Networking.Models.Vector3?)(new WebMap.Networking.Models.Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public ushort RecommendedLevel { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public uint SourceMapId { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint TargetMapId { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static void StartQuestLinkMarker(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddIcon(FlatBufferBuilder builder, uint icon) { builder.AddUint(0, icon, 0); }
  public static void AddTooltip(FlatBufferBuilder builder, StringOffset tooltipOffset) { builder.AddOffset(1, tooltipOffset.Value, 0); }
  public static void AddLevelId(FlatBufferBuilder builder, uint levelId) { builder.AddUint(2, levelId, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.Vector3> positionOffset) { builder.AddStruct(3, positionOffset.Value, 0); }
  public static void AddRecommendedLevel(FlatBufferBuilder builder, ushort recommendedLevel) { builder.AddUshort(4, recommendedLevel, 0); }
  public static void AddSourceMapId(FlatBufferBuilder builder, uint sourceMapId) { builder.AddUint(5, sourceMapId, 0); }
  public static void AddTargetMapId(FlatBufferBuilder builder, uint targetMapId) { builder.AddUint(6, targetMapId, 0); }
  public static Offset<WebMap.Networking.Models.QuestLinkMarker> EndQuestLinkMarker(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 10);  // position
    return new Offset<WebMap.Networking.Models.QuestLinkMarker>(o);
  }
}


static public class QuestLinkMarkerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Icon*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Tooltip*/, false)
      && verifier.VerifyField(tablePos, 8 /*LevelId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Position*/, 12 /*WebMap.Networking.Models.Vector3*/, 4, true)
      && verifier.VerifyField(tablePos, 12 /*RecommendedLevel*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 14 /*SourceMapId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*TargetMapId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
