// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SelectedLocation : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SelectedLocation GetRootAsSelectedLocation(ByteBuffer _bb) { return GetRootAsSelectedLocation(_bb, new SelectedLocation()); }
  public static SelectedLocation GetRootAsSelectedLocation(ByteBuffer _bb, SelectedLocation obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SelectedLocation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint MapId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int DiscoveryMask { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<WebMap.Networking.Models.SelectedLocation> CreateSelectedLocation(FlatBufferBuilder builder,
      uint map_id = 0,
      int discovery_mask = 0) {
    builder.StartTable(2);
    SelectedLocation.AddDiscoveryMask(builder, discovery_mask);
    SelectedLocation.AddMapId(builder, map_id);
    return SelectedLocation.EndSelectedLocation(builder);
  }

  public static void StartSelectedLocation(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMapId(FlatBufferBuilder builder, uint mapId) { builder.AddUint(0, mapId, 0); }
  public static void AddDiscoveryMask(FlatBufferBuilder builder, int discoveryMask) { builder.AddInt(1, discoveryMask, 0); }
  public static Offset<WebMap.Networking.Models.SelectedLocation> EndSelectedLocation(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.SelectedLocation>(o);
  }
}


static public class SelectedLocationVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MapId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*DiscoveryMask*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
