// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ServerMessage GetRootAsServerMessage(ByteBuffer _bb) { return GetRootAsServerMessage(_bb, new ServerMessage()); }
  public static ServerMessage GetRootAsServerMessage(ByteBuffer _bb, ServerMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyServerMessage(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ServerMessageVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public WebMap.Networking.Models.MessageType Type { get { int o = __p.__offset(4); return o != 0 ? (WebMap.Networking.Models.MessageType)__p.bb.GetSbyte(o + __p.bb_pos) : WebMap.Networking.Models.MessageType.MapData; } }
  public WebMap.Networking.Models.MessagePayload PayloadType { get { int o = __p.__offset(6); return o != 0 ? (WebMap.Networking.Models.MessagePayload)__p.bb.Get(o + __p.bb_pos) : WebMap.Networking.Models.MessagePayload.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public WebMap.Networking.Models.MapData PayloadAsMapData() { return Payload<WebMap.Networking.Models.MapData>().Value; }
  public WebMap.Networking.Models.Location PayloadAsLocation() { return Payload<WebMap.Networking.Models.Location>().Value; }
  public WebMap.Networking.Models.PlayerTransformAndCameraRotation PayloadAsPlayerTransformAndCameraRotation() { return Payload<WebMap.Networking.Models.PlayerTransformAndCameraRotation>().Value; }
  public WebMap.Networking.Models.SelectedLocation PayloadAsSelectedLocation() { return Payload<WebMap.Networking.Models.SelectedLocation>().Value; }
  public WebMap.Networking.Models.DiscoveryMask PayloadAsDiscoveryMask() { return Payload<WebMap.Networking.Models.DiscoveryMask>().Value; }
  public WebMap.Networking.Models.DynamicMarker PayloadAsDynamicMarker() { return Payload<WebMap.Networking.Models.DynamicMarker>().Value; }
  public WebMap.Networking.Models.DynamicMarkerList PayloadAsDynamicMarkerList() { return Payload<WebMap.Networking.Models.DynamicMarkerList>().Value; }
  public WebMap.Networking.Models.QuestLinkMarkerList PayloadAsQuestLinkMarkerList() { return Payload<WebMap.Networking.Models.QuestLinkMarkerList>().Value; }
  public WebMap.Networking.Models.FlagMarkerList PayloadAsFlagMarkerList() { return Payload<WebMap.Networking.Models.FlagMarkerList>().Value; }

  public static Offset<WebMap.Networking.Models.ServerMessage> CreateServerMessage(FlatBufferBuilder builder,
      WebMap.Networking.Models.MessageType type = WebMap.Networking.Models.MessageType.MapData,
      WebMap.Networking.Models.MessagePayload payload_type = WebMap.Networking.Models.MessagePayload.NONE,
      int payloadOffset = 0) {
    builder.StartTable(3);
    ServerMessage.AddPayload(builder, payloadOffset);
    ServerMessage.AddPayloadType(builder, payload_type);
    ServerMessage.AddType(builder, type);
    return ServerMessage.EndServerMessage(builder);
  }

  public static void StartServerMessage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddType(FlatBufferBuilder builder, WebMap.Networking.Models.MessageType type) { builder.AddSbyte(0, (sbyte)type, 0); }
  public static void AddPayloadType(FlatBufferBuilder builder, WebMap.Networking.Models.MessagePayload payloadType) { builder.AddByte(1, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(2, payloadOffset, 0); }
  public static Offset<WebMap.Networking.Models.ServerMessage> EndServerMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WebMap.Networking.Models.ServerMessage>(o);
  }
  public static void FinishServerMessageBuffer(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.ServerMessage> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedServerMessageBuffer(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.ServerMessage> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ServerMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Type*/, 1 /*WebMap.Networking.Models.MessageType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*PayloadType*/, 1 /*WebMap.Networking.Models.MessagePayload*/, 1, false)
      && verifier.VerifyUnion(tablePos, 6, 8 /*Payload*/, WebMap.Networking.Models.MessagePayloadVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
