// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StaticMarker : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static StaticMarker GetRootAsStaticMarker(ByteBuffer _bb) { return GetRootAsStaticMarker(_bb, new StaticMarker()); }
  public static StaticMarker GetRootAsStaticMarker(ByteBuffer _bb, StaticMarker obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StaticMarker __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint SubRowId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public WebMap.Networking.Models.SeString? Title { get { int o = __p.__offset(6); return o != 0 ? (WebMap.Networking.Models.SeString?)(new WebMap.Networking.Models.SeString()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public ushort? Icon { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort?)null; } }
  public WebMap.Networking.Models.Vector2? Position { get { int o = __p.__offset(10); return o != 0 ? (WebMap.Networking.Models.Vector2?)(new WebMap.Networking.Models.Vector2()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public byte? SubtextOrientation { get { int o = __p.__offset(12); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte?)null; } }
  public byte Type { get { int o = __p.__offset(14); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public WebMap.Networking.Models.StaticMarkerData DataType { get { int o = __p.__offset(16); return o != 0 ? (WebMap.Networking.Models.StaticMarkerData)__p.bb.Get(o + __p.bb_pos) : WebMap.Networking.Models.StaticMarkerData.NONE; } }
  public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(18); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public WebMap.Networking.Models.MapLinkData DataAsMapLink() { return Data<WebMap.Networking.Models.MapLinkData>().Value; }
  public WebMap.Networking.Models.MapLinkData DataAsImplicitMapLink() { return Data<WebMap.Networking.Models.MapLinkData>().Value; }
  public WebMap.Networking.Models.AetheryteData DataAsAetheryte() { return Data<WebMap.Networking.Models.AetheryteData>().Value; }
  public WebMap.Networking.Models.PlaceNameData DataAsPlaceName() { return Data<WebMap.Networking.Models.PlaceNameData>().Value; }

  public static void StartStaticMarker(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddSubRowId(FlatBufferBuilder builder, uint subRowId) { builder.AddUint(0, subRowId, 0); }
  public static void AddTitle(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.SeString> titleOffset) { builder.AddOffset(1, titleOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, ushort? icon) { builder.AddUshort(2, icon); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<WebMap.Networking.Models.Vector2> positionOffset) { builder.AddStruct(3, positionOffset.Value, 0); }
  public static void AddSubtextOrientation(FlatBufferBuilder builder, byte? subtextOrientation) { builder.AddByte(4, subtextOrientation); }
  public static void AddType(FlatBufferBuilder builder, byte type) { builder.AddByte(5, type, 0); }
  public static void AddDataType(FlatBufferBuilder builder, WebMap.Networking.Models.StaticMarkerData dataType) { builder.AddByte(6, (byte)dataType, 0); }
  public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(7, dataOffset, 0); }
  public static Offset<WebMap.Networking.Models.StaticMarker> EndStaticMarker(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 10);  // position
    return new Offset<WebMap.Networking.Models.StaticMarker>(o);
  }

  public static VectorOffset CreateSortedVectorOfStaticMarker(FlatBufferBuilder builder, Offset<StaticMarker>[] offsets) {
    Array.Sort(offsets,
      (Offset<StaticMarker> o1, Offset<StaticMarker> o2) =>
        new StaticMarker().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).SubRowId.CompareTo(new StaticMarker().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).SubRowId));
    return builder.CreateVectorOfTables(offsets);
  }

  public static StaticMarker? __lookup_by_key(int vectorLocation, uint key, ByteBuffer bb) {
    StaticMarker obj_ = new StaticMarker();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_.SubRowId.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
}


static public class StaticMarkerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SubRowId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*Title*/, WebMap.Networking.Models.SeStringVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*Icon*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*Position*/, 8 /*WebMap.Networking.Models.Vector2*/, 4, true)
      && verifier.VerifyField(tablePos, 12 /*SubtextOrientation*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 14 /*Type*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 16 /*DataType*/, 1 /*WebMap.Networking.Models.StaticMarkerData*/, 1, false)
      && verifier.VerifyUnion(tablePos, 16, 18 /*Data*/, WebMap.Networking.Models.StaticMarkerDataVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
