// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

public enum StaticMarkerData : byte
{
  NONE = 0,
  MapLink = 1,
  ImplicitMapLink = 2,
  Aetheryte = 3,
  PlaceName = 4,
};



static public class StaticMarkerDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((StaticMarkerData)typeId)
    {
      case StaticMarkerData.MapLink:
        result = WebMap.Networking.Models.MapLinkDataVerify.Verify(verifier, tablePos);
        break;
      case StaticMarkerData.ImplicitMapLink:
        result = WebMap.Networking.Models.MapLinkDataVerify.Verify(verifier, tablePos);
        break;
      case StaticMarkerData.Aetheryte:
        result = WebMap.Networking.Models.AetheryteDataVerify.Verify(verifier, tablePos);
        break;
      case StaticMarkerData.PlaceName:
        result = WebMap.Networking.Models.PlaceNameDataVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
