// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WebMap.Networking.Models
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Transform : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Transform __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public WebMap.Networking.Models.Vector3 Position { get { return (new WebMap.Networking.Models.Vector3()).__assign(__p.bb_pos + 0, __p.bb); } }
  public float Rotation { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<WebMap.Networking.Models.Transform> CreateTransform(FlatBufferBuilder builder, float position_X, float position_Y, float position_Z, float Rotation) {
    builder.Prep(4, 16);
    builder.PutFloat(Rotation);
    builder.Prep(4, 12);
    builder.PutFloat(position_Z);
    builder.PutFloat(position_Y);
    builder.PutFloat(position_X);
    return new Offset<WebMap.Networking.Models.Transform>(builder.Offset);
  }
}


}
